### ISSUE TITLE
"kurven-balken" im header

### ISSUE THREAD

**Issue by jemand771** [d39s/bauprojekt#10]
aktuell:
![image](https://github.com/d39s/bauprojekt/assets/19669567/8f4a2df8-5735-437d-9d22-3f4b7bc8ea47)

gewünscht:
![image](https://github.com/d39s/bauprojekt/assets/19669567/7bff2ad5-8050-429b-81c3-f7055c11df8f)

-> header bleibt sticky; die section divider alignen mit dem header und sehen (hoffentlich) hübsch aus

**Comment by DSczyrba** [comment]
![image](https://github.com/d39s/bauprojekt/assets/45792945/07a1e3f0-b08f-4206-a6a7-23da5fe6fadd)

**Comment by jemand771** [comment]
https://github.com/michswo/bauprojekt/pull/1
https://github.com/michswo/bauprojekt/pull/1/commits/e17812d626eac5dd0820a3098ae1f63cd8f594bf
